name: Build Release Candidates

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
  linux:
    uses: ./.github/workflows/manager/linux/build_release_candidate.yml
    secrets:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
