name: Build Linux Release Candidate

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SENTRY_DSN:
        required: true

jobs:
  windows_release_build:
    name: Build Linux Release Installer
    runs-on: windows-20.04
    timeout-minutes: 10
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Linux Release Candidate
        run: npm run action server_manager/electron_app/release_linux

      - name: Upload Linux Release Candidate
        uses: actions/upload-artifact@v2
        with:
          name: manager_linux_release_${{ github.sha }}
          path: build/dist
          if-no-files-found: error
