name: Release Server

on:
  push:
    tag: server-v*
  schedule:
    - cron: '0 0 * * *'

jobs:
  release_shadowbox:
    name: Release Shadowbox Canary
    runs-on: ubuntu-20.04
    environment: Deploy Shadowbox Canary

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Show Environment Info
        run: yarn -v

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Check yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --prefer-offline

      - name: Shadowbox Unit Tests
        run: yarn do shadowbox/test

      - name: Shadowbox Integration Tests
        run: |
          yarn do shadowbox/server/build
          yarn do shadowbox/integration_test/run

      - name: Build Shadowbox Container
        run: yarn do shadowbox/docker/build

      - name: Log in to Quay
        env:
          QUAY_IO_USERNAME: ${{ secrets.QUAY_IO_USERNAME }}
          QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
        run: docker login quay.io -u="$QUAY_IO_USERNAME" -p="$QUAY_IO_PASSWORD"

      - name: Deploy
        run: |
          PROD=${{ startsWith(github.ref, 'refs/tags/server-v') && true || '' }}
          TAG=$([[ -z $PROD ]] && echo "daily" || echo $(date -I))
          echo "Tagging image with tag: $TAG"
          docker tag outline/shadowbox quay.io/outline/shadowbox:TAG
          docker push quay.io/outline/shadowbox:TAG
